log_path: logs/*.log
server:
  ip: 192.168.1.100
log_format:
  type: web
  timestamp_format: '%d/%b/%Y:%H:%M:%S %z'
  fields:
    src_ip: (\d+\.\d+\.\d+\.\d+)
    timestamp: \[(.*?)\]
    request_line: '"([A-Z]+\s+[^\s]+\s+HTTP/[\d\.]+)"'
    request_method: '"([A-Z]+)\s'
    request_path: '"[A-Z]+\s+([^\s]+)\s+'
    http_version: '(HTTP/\d\.\d)"'
    status_code: '"\s+(\d{3})\s+'
    response_size: '\s+(\d+)\s+'
    processing_time: '\s+([\d.]+)\s+'
    user_agent: '"user_agent":"([^"]*)"'
    client_info: '{(.*?)}'
rule_dir: rules
rules:
  default_severity: medium
analysis:
  batch_size: 1000
  max_events: 100
  memory_limit_mb: 500
context_lines: 5
ai_analysis:
  high_risk_only: false
  successful_attacks_only: false
  success_status_codes:
  - '200'
  - '201'
  - '202'
  - '204'
  - '301'
  - '302'
  - '304'
  - '403'
  - '404'
  - '405'
  - '500'
  max_ai_analysis: 5
  high_risk_severity: high
output_dir: output
report_type: html
report:
  template: templates/report_template.html
  output_format: html
  output_directory: reports
deepseek:
  api_key: sk-vygfmyaluapwxkzacchicoxkhovgwqurwprvjjdfvdbptxox
  model: deepseek-ai/DeepSeek-V3
  base_url: https://api.siliconflow.cn/v1/chat/completions
  timeout: 30
  max_tokens: 2048
ai:
  type: cloud
  local_provider: ollama
  cloud_provider: deepseek
ollama:
  model: deepseek-r1:14b
  base_url: http://localhost:11434/api/chat
  timeout: 60
geoip_db_path: /Users/wooluo/DEV/SSlogs/config/GeoLite2-Country.mmdb
