name: CORS配置错误检测
pattern: 'Access-Control-Allow-Origin: (\*|http://|https://)([^\s]+\.com|[^\s]+\.net|[^\s]+\.org)'
severity: high
category: misconfiguration
description: 检测不安全的跨域资源共享(CORS)配置，包括允许任意来源(*)或未授权域名的跨域访问